AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.umaxcode::springboot-crud-with-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Parameters:
  AwsAccessKey:
    Type: String
    Description: Enter access key
  AwsSecretKey:
    Type: String
    Description: Enter secret key
  DynamoDBPostTable:
    Description: Dynamodb table for post
    Type: String
    Default: posts

Resources:
  SpringbootCrudWithLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.umaxcode.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBPostTable
          IAM_USER_ACCESS_KEY: !Ref AwsAccessKey
          IAM_USER_SECRET_KEY: !Ref AwsSecretKey
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBPostTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  SpringbootCrudWithLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringbootCrudWithLambdaApi
